const catchError = require("../utility/catch-error");

exports.getHistory = catchError(async (req, res, next) => {});
